---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: kafka-broker0
  namespace: kafka
spec:
  template:
    metadata:
      labels:
        app: kafka
        id: "0"
    spec:
      containers:
      - name: kafka
        image: wurstmeister/kafka
        ports:
        - containerPort: 9092
        env:
        - name: KAFKA_ADVERTISED_PORT
          value: "32092"
        - name: KAFKA_ADVERTISED_HOST_NAME
          value: 182.208.133.108
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: zoo1:2181
        - name: KAFKA_BROKER_ID
          value: "0"
        - name: KAFKA_CREATE_TOPICS
          value: admintome-test:1:1
        volumeMounts:
          - name: datadir
            mountPath: /kafka
      volumes:
        - name: datadir
          persistentVolumeClaim:
            claimName: pvc-kafka
 
