---
apiVersion: v1
kind: Service
metadata:
  name: kafka-service
  labels:
    name: kafka
  namespace: kafka
spec:
  type: NodePort
  ports:
  - port: 9092
    targetPort: 9092
    nodePort: 32092
    name: kafka-port
    protocol: TCP
  selector:
    app: kafka
    id: "0"
